# Generated by Django 5.0.6 on 2024-05-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='main_app.language'),
        ),
    ]
